"""Вопрос и ответы

Revision ID: dad6a27b92bf
Revises: d715dcde19de
Create Date: 2025-09-01 21:39:15.666933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad6a27b92bf'
down_revision: Union[str, Sequence[str], None] = 'd715dcde19de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
                INSERT INTO questionstable (id, text, created_at) VALUES
                (1, 'What is your duty?', '2025-09-01');
               """)
    op.execute("""
                INSERT INTO answerstable (id, question_id, text, user_id, created_at) VALUES
                (1, 1, 'To serve The Emperors will', 'Капеллан', '2025-09-01'),
                (2, 1, 'Ну, допустим, служить Воле Императора', 'Капеллан', '2025-09-01');
               """)
    op.execute("""
                CREATE DATABASE test
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM questionstable WHERE id = 1;
    """)
    op.execute("""
        DELETE FROM questionstable WHERE id IN (1, 2);
    """)
    op.drop_table("test")
    # ### end Alembic commands ###
